project:
  type: website
  resources: static

website:
  title: "Ryan Wesslen" 
  site-url: https://wesslen.netlify.app
  description: "Ryan Wesslen's personal Blog."
  navbar:
    # left:
    #   - text: Publications
    #     href: publications.qmd
    #   - text: Teaching
    #     href: teaching.qmd
    right:
      - icon: envelope
        href: mailto:rwesslen@gmail.com
      - icon: linkedin
        href: https://linkedin.com/in/ryanwesslen
      - icon: github
        href: https://github.com/wesslen
      - text: "{{< ai google-scholar size=xl >}}"
        href: https://scholar.google.com/citations?user=F40SbCkAAAAJ&hl
  google-analytics: 
    tracking-id: "G-VX7KRFGCZW"
    anonymize-ip: true
  twitter-card: 
    image: thumbnail_blog.png
    card-style: summary_large_image
    creator: "@ryanwesslen"
  search: false

format:
  html:
    theme: litera
    css: styles.css

execute:
  freeze: auto